
-
  branches:
    only:
      - release
  
  version: 4.9.{build}
  
  os: Visual Studio 2015

  install: 
    - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
  
  before_build: 
    - cmd: nuget restore RefactoringEssentials.sln

  build_script:
    - msbuild RefactoringEssentials.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
  
  after_test:
    - cmd: nuget pack bin\Release\RefactoringEssentials.nuspec -NoPackageAnalysis -BasePath bin\Release -OutputDirectory bin\Release
    - cmd: nuget pack bin\Release\RefactoringEssentials.Library.nuspec -NoPackageAnalysis -BasePath bin\Release -OutputDirectory bin\Release
  
  artifacts:
    - path: bin\**\*.nupkg
      name: NuGet
  
    - path: bin\**\*.vsix
      name: VSIX

-
  branches:
    only:
      - master
  
  version: 4.9.{build}
  
  os: Visual Studio 2015
  
  install: 
    - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
  
  before_build: 
    - ps: Vsix-IncrementVsixVersion ".\Vsix\source.extension.vsixmanifest" | Vsix-UpdateBuildVersion
    - cmd: nuget restore RefactoringEssentials.sln
  
  build_script:
    - msbuild RefactoringEssentials.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
  
  after_test:
    - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
 